version: '3.3'

services:
  db:
    labels:
      kompose.volume.size: 10Gi
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=change_me
      - DBDATA=/opt/data
    volumes:
      - db_data:/opt
  webserver:
    container_name: webserver
    #    image: cronosd
    image: alexwerner/backend:0.1
    ports:
      - "3001:3001"
    volumes:
      - server_data:/opt
  jmes_node:
    container_name: validator-jmes_node
    #    image: cronosd
    image: alexwerner/cronosd:0.1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "26656:26656"
      - "26657:26657"
      - "30303:30303"
    volumes:
      - jmes_data_current:/home/cronosd/.local/share/cronosd/
    entrypoint:
      - /bin/sh
      - -xc
      - pystarport serve --config ./cronos-devnet.yaml
  blockscout:
    labels:
      kompose.service.expose: "true"
      kompose.volume.size: 10Gi
    container_name: blockscout
    # Change Image (based on local image constructed on running blockexplorer-evm/'s docker build -f ./docker/Dockerfile -t blockexplorer .
#    image: 44dc5b026f36
    image: alexwerner/blockexplorer:0.1
    environment:
      - COIN=JMES
      - MIX_ENV=prod
      - DATABASE_URL=postgresql://postgres:change_me@db/blockscout
      - ETHEREUM_JSONRPC_VARIANT=parity
      - ETHEREUM_JSONRPC_HTTP_URL=http://jmes_node:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://jmes_node:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://jmes_node:8546
      - ECTO_USE_SSL=false
    ports:
      - "80:4000"

    entrypoint:
      - /bin/sh
      - -xc
    command:
      - |
        echo 'Blockscout' && mix do ecto.create; mix do ecto.migrate ;  mix phx.server; tail -f /dev/null



volumes:
  server_data:
  db_data:
  jmes_data_current:

configs:
  ethconf:
    file: ./settings/current/archive-node.toml
  bootpeers:
    file: ./settings/current/bootstrap.txt
  genesis:
    file: ./settings/current/genesis.json
